const guests = [
    { name: "Anita", rsvp: true },
    { name: "Carolina", rsvp: true },
    { name: "Pedro", rsvp: false },
    { name: "Loreto", rsvp: true },
    { name: "Nicolás", rsvp: false },
    { name: "Daniela", rsvp: true },
    { name: "Tati", rsvp: true },
    { name: "Weli", rsvp: false },
    { name: "Marcela", rsvp: true },
    { name: "Sergio", rsvp: false },
    { name: "Andrés", rsvp: true },
    { name: "Francisco", rsvp: true },
    { name: "Angélica", rsvp: false },
    { name: "Oscar", rsvp: true },
    { name: "María Paz", rsvp: false },
    { name: "Rodrigo", rsvp: true },
    { name: "Rosario", rsvp: true },
    { name: "Vicente", rsvp: false },
    { name: "Pablo", rsvp: true },
    { name: "Francisca", rsvp: false },
    { name: "Pablo", rsvp: true },
    { name: "Tomás", rsvp: true },
    { name: "Barbara", rsvp: false },
    { name: "Ignacio", rsvp: true },
    { name: "Cristobal", rsvp: false },
    { name: "Carla", rsvp: true },
    { name: "Diego", rsvp: true },
    { name: "Tía Caroli", rsvp: false },
    { name: "María Ignacia", rsvp: true },
    { name: "Sofía", rsvp: false },
    { name: "Gina", rsvp: false },
    { name: "Luis", rsvp: true },
    { name: "Jorge", rsvp: true },
    { name: "Carmen", rsvp: false },
    { name: "Santino", rsvp: true },
    { name: "Jorge", rsvp: false },
    { name: "Mónica", rsvp: true },
    { name: "Manena", rsvp: true },
    { name: "Tata", rsvp: false },
    { name: "Alejandra", rsvp: true },
    { name: "Juan Ignacio", rsvp: false },
    { name: "Joaquin", rsvp: false },
    { name: "Teresita", rsvp: false },
    { name: "Rodrigo", rsvp: true },
    { name: "Sonia", rsvp: true },
    { name: "Ema", rsvp: false },
    { name: "Manuel", rsvp: true },
    { name: "Jaime", rsvp: false },
    { name: "Claudia", rsvp: true },
    { name: "Francesca", rsvp: true },
    { name: "Andrea", rsvp: false },
];

export const getRandomGuestName = () => {
    const randomIndex = Math.floor(Math.random() * guests.length);
    return guests[randomIndex].name;
};